"""remove refresh_token from user

Revision ID: 2fab68313641
Revises: c1bb2e1925e1
Create Date: 2026-05-20 17:29:21.441772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fab68313641'
down_revision: Union[str, Sequence[str], None] = 'c1bb2e1925e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
